// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agents.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (user_id, provisioned_with_key_id, metadata, notes)
VALUES ($1, $2, $3, $4) RETURNING id, user_id, provisioned_with_key_id, status, cert_fingerprint, registered_at, last_seen_at, last_ip_address, metadata, notes
`

type CreateAgentParams struct {
	UserID               pgtype.UUID `json:"user_id"`
	ProvisionedWithKeyID pgtype.UUID `json:"provisioned_with_key_id"`
	Metadata             []byte      `json:"metadata"`
	Notes                pgtype.Text `json:"notes"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.UserID,
		arg.ProvisionedWithKeyID,
		arg.Metadata,
		arg.Notes,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProvisionedWithKeyID,
		&i.Status,
		&i.CertFingerprint,
		&i.RegisteredAt,
		&i.LastSeenAt,
		&i.LastIpAddress,
		&i.Metadata,
		&i.Notes,
	)
	return i, err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, user_id, provisioned_with_key_id, status, cert_fingerprint, registered_at, last_seen_at, last_ip_address, metadata, notes FROM agents WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAgentByID(ctx context.Context, id pgtype.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProvisionedWithKeyID,
		&i.Status,
		&i.CertFingerprint,
		&i.RegisteredAt,
		&i.LastSeenAt,
		&i.LastIpAddress,
		&i.Metadata,
		&i.Notes,
	)
	return i, err
}

const listAgentsByUser = `-- name: ListAgentsByUser :many
SELECT id, user_id, provisioned_with_key_id, status, cert_fingerprint, registered_at, last_seen_at, last_ip_address, metadata, notes FROM agents WHERE user_id = $1 ORDER BY registered_at DESC
`

func (q *Queries) ListAgentsByUser(ctx context.Context, userID pgtype.UUID) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProvisionedWithKeyID,
			&i.Status,
			&i.CertFingerprint,
			&i.RegisteredAt,
			&i.LastSeenAt,
			&i.LastIpAddress,
			&i.Metadata,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentCertFingerprint = `-- name: UpdateAgentCertFingerprint :exec
UPDATE agents SET cert_fingerprint = $2 WHERE id = $1
`

type UpdateAgentCertFingerprintParams struct {
	ID              pgtype.UUID `json:"id"`
	CertFingerprint pgtype.Text `json:"cert_fingerprint"`
}

func (q *Queries) UpdateAgentCertFingerprint(ctx context.Context, arg UpdateAgentCertFingerprintParams) error {
	_, err := q.db.Exec(ctx, updateAgentCertFingerprint, arg.ID, arg.CertFingerprint)
	return err
}

const updateAgentLastSeen = `-- name: UpdateAgentLastSeen :exec
UPDATE agents SET last_seen_at = $2, last_ip_address = $3 WHERE id = $1
`

type UpdateAgentLastSeenParams struct {
	ID            pgtype.UUID      `json:"id"`
	LastSeenAt    pgtype.Timestamp `json:"last_seen_at"`
	LastIpAddress *netip.Addr      `json:"last_ip_address"`
}

func (q *Queries) UpdateAgentLastSeen(ctx context.Context, arg UpdateAgentLastSeenParams) error {
	_, err := q.db.Exec(ctx, updateAgentLastSeen, arg.ID, arg.LastSeenAt, arg.LastIpAddress)
	return err
}

const updateAgentStatus = `-- name: UpdateAgentStatus :exec
UPDATE agents SET status = $2 WHERE id = $1
`

type UpdateAgentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status AgentStatus `json:"status"`
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) error {
	_, err := q.db.Exec(ctx, updateAgentStatus, arg.ID, arg.Status)
	return err
}
