// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent_certificates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkCertificateValid = `-- name: CheckCertificateValid :one
SELECT id, agent_id, user_id, is_active, revoked_at, not_after
FROM agent_certificates
WHERE agent_id = $1
  AND is_active = true
  AND revoked_at IS NULL
  AND not_after > NOW()
LIMIT 1
`

type CheckCertificateValidRow struct {
	ID        pgtype.UUID      `json:"id"`
	AgentID   string           `json:"agent_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	IsActive  bool             `json:"is_active"`
	RevokedAt pgtype.Timestamp `json:"revoked_at"`
	NotAfter  pgtype.Timestamp `json:"not_after"`
}

func (q *Queries) CheckCertificateValid(ctx context.Context, agentID string) (CheckCertificateValidRow, error) {
	row := q.db.QueryRow(ctx, checkCertificateValid, agentID)
	var i CheckCertificateValidRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.UserID,
		&i.IsActive,
		&i.RevokedAt,
		&i.NotAfter,
	)
	return i, err
}

const createAgentCertificate = `-- name: CreateAgentCertificate :one
INSERT INTO agent_certificates (
    user_id,
    agent_id,
    serial_number,
    subject_common_name,
    not_before,
    not_after,
    cert_pem,
    key_pem
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, user_id, agent_id, serial_number, subject_common_name, not_before, not_after, cert_pem, key_pem, is_active, revoked_at, revoked_reason, created_at
`

type CreateAgentCertificateParams struct {
	UserID            pgtype.UUID      `json:"user_id"`
	AgentID           string           `json:"agent_id"`
	SerialNumber      string           `json:"serial_number"`
	SubjectCommonName string           `json:"subject_common_name"`
	NotBefore         pgtype.Timestamp `json:"not_before"`
	NotAfter          pgtype.Timestamp `json:"not_after"`
	CertPem           string           `json:"cert_pem"`
	KeyPem            string           `json:"key_pem"`
}

func (q *Queries) CreateAgentCertificate(ctx context.Context, arg CreateAgentCertificateParams) (AgentCertificate, error) {
	row := q.db.QueryRow(ctx, createAgentCertificate,
		arg.UserID,
		arg.AgentID,
		arg.SerialNumber,
		arg.SubjectCommonName,
		arg.NotBefore,
		arg.NotAfter,
		arg.CertPem,
		arg.KeyPem,
	)
	var i AgentCertificate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.SerialNumber,
		&i.SubjectCommonName,
		&i.NotBefore,
		&i.NotAfter,
		&i.CertPem,
		&i.KeyPem,
		&i.IsActive,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCertificate = `-- name: DeleteCertificate :exec
DELETE FROM agent_certificates
WHERE agent_id = $1
`

func (q *Queries) DeleteCertificate(ctx context.Context, agentID string) error {
	_, err := q.db.Exec(ctx, deleteCertificate, agentID)
	return err
}

const getCertificateByAgentID = `-- name: GetCertificateByAgentID :one
SELECT id, user_id, agent_id, serial_number, subject_common_name, not_before, not_after, cert_pem, key_pem, is_active, revoked_at, revoked_reason, created_at FROM agent_certificates
WHERE agent_id = $1
LIMIT 1
`

func (q *Queries) GetCertificateByAgentID(ctx context.Context, agentID string) (AgentCertificate, error) {
	row := q.db.QueryRow(ctx, getCertificateByAgentID, agentID)
	var i AgentCertificate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.SerialNumber,
		&i.SubjectCommonName,
		&i.NotBefore,
		&i.NotAfter,
		&i.CertPem,
		&i.KeyPem,
		&i.IsActive,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getCertificateByID = `-- name: GetCertificateByID :one
SELECT id, user_id, agent_id, serial_number, subject_common_name, not_before, not_after, cert_pem, key_pem, is_active, revoked_at, revoked_reason, created_at FROM agent_certificates
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCertificateByID(ctx context.Context, id pgtype.UUID) (AgentCertificate, error) {
	row := q.db.QueryRow(ctx, getCertificateByID, id)
	var i AgentCertificate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.SerialNumber,
		&i.SubjectCommonName,
		&i.NotBefore,
		&i.NotAfter,
		&i.CertPem,
		&i.KeyPem,
		&i.IsActive,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getCertificateBySerial = `-- name: GetCertificateBySerial :one
SELECT id, user_id, agent_id, serial_number, subject_common_name, not_before, not_after, cert_pem, key_pem, is_active, revoked_at, revoked_reason, created_at FROM agent_certificates
WHERE serial_number = $1
LIMIT 1
`

func (q *Queries) GetCertificateBySerial(ctx context.Context, serialNumber string) (AgentCertificate, error) {
	row := q.db.QueryRow(ctx, getCertificateBySerial, serialNumber)
	var i AgentCertificate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.SerialNumber,
		&i.SubjectCommonName,
		&i.NotBefore,
		&i.NotAfter,
		&i.CertPem,
		&i.KeyPem,
		&i.IsActive,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const listAllCertificates = `-- name: ListAllCertificates :many
SELECT id, user_id, agent_id, serial_number, subject_common_name, not_before, not_after, cert_pem, key_pem, is_active, revoked_at, revoked_reason, created_at FROM agent_certificates
ORDER BY created_at DESC
`

func (q *Queries) ListAllCertificates(ctx context.Context) ([]AgentCertificate, error) {
	rows, err := q.db.Query(ctx, listAllCertificates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentCertificate{}
	for rows.Next() {
		var i AgentCertificate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.SerialNumber,
			&i.SubjectCommonName,
			&i.NotBefore,
			&i.NotAfter,
			&i.CertPem,
			&i.KeyPem,
			&i.IsActive,
			&i.RevokedAt,
			&i.RevokedReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesByUser = `-- name: ListCertificatesByUser :many
SELECT id, user_id, agent_id, serial_number, subject_common_name, not_before, not_after, cert_pem, key_pem, is_active, revoked_at, revoked_reason, created_at FROM agent_certificates
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCertificatesByUser(ctx context.Context, userID pgtype.UUID) ([]AgentCertificate, error) {
	rows, err := q.db.Query(ctx, listCertificatesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentCertificate{}
	for rows.Next() {
		var i AgentCertificate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.SerialNumber,
			&i.SubjectCommonName,
			&i.NotBefore,
			&i.NotAfter,
			&i.CertPem,
			&i.KeyPem,
			&i.IsActive,
			&i.RevokedAt,
			&i.RevokedReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCertificate = `-- name: RevokeCertificate :one
UPDATE agent_certificates
SET revoked_at = NOW(),
    revoked_reason = $2,
    is_active = false
WHERE agent_id = $1
RETURNING id, user_id, agent_id, serial_number, subject_common_name, not_before, not_after, cert_pem, key_pem, is_active, revoked_at, revoked_reason, created_at
`

type RevokeCertificateParams struct {
	AgentID       string      `json:"agent_id"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeCertificate(ctx context.Context, arg RevokeCertificateParams) (AgentCertificate, error) {
	row := q.db.QueryRow(ctx, revokeCertificate, arg.AgentID, arg.RevokedReason)
	var i AgentCertificate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.SerialNumber,
		&i.SubjectCommonName,
		&i.NotBefore,
		&i.NotAfter,
		&i.CertPem,
		&i.KeyPem,
		&i.IsActive,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}
