// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: provisioning_keys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProvisioningKey = `-- name: CreateProvisioningKey :one
INSERT INTO provisioning_keys (key_hash, user_id, max_uses, expires_at, notes)
VALUES ($1, $2, $3, $4, $5) RETURNING id, key_hash, user_id, status, max_uses, used_count, expires_at, created_at, updated_at, revoked_at, notes
`

type CreateProvisioningKeyParams struct {
	KeyHash   string           `json:"key_hash"`
	UserID    pgtype.UUID      `json:"user_id"`
	MaxUses   int32            `json:"max_uses"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Notes     pgtype.Text      `json:"notes"`
}

func (q *Queries) CreateProvisioningKey(ctx context.Context, arg CreateProvisioningKeyParams) (ProvisioningKey, error) {
	row := q.db.QueryRow(ctx, createProvisioningKey,
		arg.KeyHash,
		arg.UserID,
		arg.MaxUses,
		arg.ExpiresAt,
		arg.Notes,
	)
	var i ProvisioningKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.UserID,
		&i.Status,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.Notes,
	)
	return i, err
}

const expireOldKeys = `-- name: ExpireOldKeys :exec
UPDATE provisioning_keys
SET status = 'expired'::provisioning_key_status, updated_at = NOW()
WHERE status = 'active' AND expires_at < NOW()
`

func (q *Queries) ExpireOldKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireOldKeys)
	return err
}

const getProvisioningKeyByHash = `-- name: GetProvisioningKeyByHash :one
SELECT id, key_hash, user_id, status, max_uses, used_count, expires_at, created_at, updated_at, revoked_at, notes FROM provisioning_keys
WHERE key_hash = $1 AND status = 'active' LIMIT 1
`

func (q *Queries) GetProvisioningKeyByHash(ctx context.Context, keyHash string) (ProvisioningKey, error) {
	row := q.db.QueryRow(ctx, getProvisioningKeyByHash, keyHash)
	var i ProvisioningKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.UserID,
		&i.Status,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.Notes,
	)
	return i, err
}

const incrementKeyUsage = `-- name: IncrementKeyUsage :exec
UPDATE provisioning_keys
SET used_count = used_count + 1,
    status = CASE WHEN used_count + 1 >= max_uses
                  THEN 'exhausted'::provisioning_key_status
                  ELSE status END,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementKeyUsage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementKeyUsage, id)
	return err
}

const listProvisioningKeysByUser = `-- name: ListProvisioningKeysByUser :many
SELECT id, key_hash, user_id, status, max_uses, used_count, expires_at, created_at, updated_at, revoked_at, notes FROM provisioning_keys WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProvisioningKeysByUser(ctx context.Context, userID pgtype.UUID) ([]ProvisioningKey, error) {
	rows, err := q.db.Query(ctx, listProvisioningKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProvisioningKey{}
	for rows.Next() {
		var i ProvisioningKey
		if err := rows.Scan(
			&i.ID,
			&i.KeyHash,
			&i.UserID,
			&i.Status,
			&i.MaxUses,
			&i.UsedCount,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeProvisioningKey = `-- name: RevokeProvisioningKey :exec
UPDATE provisioning_keys
SET status = 'revoked'::provisioning_key_status, revoked_at = NOW(), updated_at = NOW()
WHERE id = $1 AND user_id = $2
`

type RevokeProvisioningKeyParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokeProvisioningKey(ctx context.Context, arg RevokeProvisioningKeyParams) error {
	_, err := q.db.Exec(ctx, revokeProvisioningKey, arg.ID, arg.UserID)
	return err
}
