// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckCertificateValid(ctx context.Context, agentID string) (CheckCertificateValidRow, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAgentCertificate(ctx context.Context, arg CreateAgentCertificateParams) (AgentCertificate, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCertificate(ctx context.Context, agentID string) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetCertificateByAgentID(ctx context.Context, agentID string) (AgentCertificate, error)
	GetCertificateByID(ctx context.Context, id pgtype.UUID) (AgentCertificate, error)
	GetCertificateBySerial(ctx context.Context, serialNumber string) (AgentCertificate, error)
	GetCertificateBySyncKey(ctx context.Context, syncKey pgtype.UUID) (AgentCertificate, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAllCertificates(ctx context.Context) ([]AgentCertificate, error)
	ListCertificatesByUser(ctx context.Context, userID pgtype.UUID) ([]AgentCertificate, error)
	ListUsersPaginated(ctx context.Context, arg ListUsersPaginatedParams) ([]User, error)
	RegenerateSyncKey(ctx context.Context, arg RegenerateSyncKeyParams) (AgentCertificate, error)
	RevokeCertificate(ctx context.Context, arg RevokeCertificateParams) (AgentCertificate, error)
}

var _ Querier = (*Queries)(nil)
