// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proxy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType defines the type of message
type MessageType int32

const (
	MessageType_UNKNOWN MessageType = 0
	// Agent sends PING to keep connection alive
	MessageType_PING MessageType = 1
	// Server responds with PONG
	MessageType_PONG MessageType = 2
	// Server sends REQUEST to forward to local services
	MessageType_REQUEST MessageType = 3
	// Agent sends RESPONSE back to server
	MessageType_RESPONSE MessageType = 4
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "PING",
		2: "PONG",
		3: "REQUEST",
		4: "RESPONSE",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":  0,
		"PING":     1,
		"PONG":     2,
		"REQUEST":  3,
		"RESPONSE": 4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proxy_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{0}
}

// ProxyMessage represents a message in the stream
type ProxyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // Unique message ID
	Type          MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=proxy.MessageType" json:"type,omitempty"`                                                           // Message type
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                                                                             // Message payload
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyMessage) Reset() {
	*x = ProxyMessage{}
	mi := &file_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyMessage) ProtoMessage() {}

func (x *ProxyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyMessage.ProtoReflect.Descriptor instead.
func (*ProxyMessage) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProxyMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

func (x *ProxyMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProxyMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proxy_proto protoreflect.FileDescriptor

const file_proxy_proto_rawDesc = "" +
	"\n" +
	"\vproxy.proto\x12\x05proxy\"\xdc\x01\n" +
	"\fProxyMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.proxy.MessageTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12=\n" +
	"\bmetadata\x18\x04 \x03(\v2!.proxy.ProxyMessage.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*I\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04PING\x10\x01\x12\b\n" +
	"\x04PONG\x10\x02\x12\v\n" +
	"\aREQUEST\x10\x03\x12\f\n" +
	"\bRESPONSE\x10\x042F\n" +
	"\fProxyService\x126\n" +
	"\x06Stream\x12\x13.proxy.ProxyMessage\x1a\x13.proxy.ProxyMessage(\x010\x01B'Z%github.com/EternisAI/silo-proxy/protob\x06proto3"

var (
	file_proxy_proto_rawDescOnce sync.Once
	file_proxy_proto_rawDescData []byte
)

func file_proxy_proto_rawDescGZIP() []byte {
	file_proxy_proto_rawDescOnce.Do(func() {
		file_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)))
	})
	return file_proxy_proto_rawDescData
}

var file_proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proxy_proto_goTypes = []any{
	(MessageType)(0),     // 0: proxy.MessageType
	(*ProxyMessage)(nil), // 1: proxy.ProxyMessage
	nil,                  // 2: proxy.ProxyMessage.MetadataEntry
}
var file_proxy_proto_depIdxs = []int32{
	0, // 0: proxy.ProxyMessage.type:type_name -> proxy.MessageType
	2, // 1: proxy.ProxyMessage.metadata:type_name -> proxy.ProxyMessage.MetadataEntry
	1, // 2: proxy.ProxyService.Stream:input_type -> proxy.ProxyMessage
	1, // 3: proxy.ProxyService.Stream:output_type -> proxy.ProxyMessage
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proxy_proto_init() }
func file_proxy_proto_init() {
	if File_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proxy_proto_goTypes,
		DependencyIndexes: file_proxy_proto_depIdxs,
		EnumInfos:         file_proxy_proto_enumTypes,
		MessageInfos:      file_proxy_proto_msgTypes,
	}.Build()
	File_proxy_proto = out.File
	file_proxy_proto_goTypes = nil
	file_proxy_proto_depIdxs = nil
}
